export const nation = [
    {"label":"土家族","value":"TJ","num":"15"},
    {"label":"土族","value":"TU","num":"30"},
    {"label":"门巴族","value":"MB","num":"54"},
    {"label":"水族","value":"SU","num":"25"},
    {"label":"毛南族","value":"MN","num":"36"},
    {"label":"乌兹别克族","value":"UZ","num":"43"},
    {"label":"布依族","value":"BY","num":"09"},
    {"label":"布朗族","value":"BL","num":"34"},
    {"label":"东乡族","value":"DX","num":"26"},
    {"label":"仡佬族","value":"GL","num":"37"},
    {"label":"仫佬族","value":"ML","num":"32"},
    {"label":"白族","value":"BA","num":"14"},
    {"label":"汉族","value":"HA","num":"01"},
    {"label":"达斡尔族","value":"DU","num":"31"},
    {"label":"回族","value":"HU","num":"03"},
    {"label":"佤族","value":"VA","num":"21"},
    {"label":"壮族","value":"ZH","num":"08"},
    {"label":"羌族","value":"QI","num":"33"},
    {"label":"阿昌族","value":"AC","num":"29"},
    {"label":"纳西族","value":"NX","num":"27"},
    {"label":"拉祜族","value":"LH","num":"24"},
    {"label":"苗族","value":"MH","num":"06"},
    {"label":"侗族","value":"DO","num":"12"},
    {"label":"京族","value":"GI","num":"49"},
    {"label":"柯尔克孜族","value":"KG","num":"29"},
    {"label":"哈尼族","value":"HN","num":"16"},
    {"label":"哈萨克族","value":"KZ","num":"17"},
    {"label":"保安族","value":"BN","num":"47"},
    {"label":"俄罗斯族","value":"RS","num":"44"},
    {"label":"独龙族","value":"DR","num":"51"},
    {"label":"怒族","value":"NU","num":"42"},
    {"label":"珞巴族","value":"LB","num":"55"},
    {"label":"高山族","value":"GS","num":"23"},
    {"label":"基诺族","value":"JN","num":"56"},
    {"label":"鄂伦春族","value":"OR","num":"52"},
    {"label":"鄂温克族","value":"EW","num":"45"},
    {"label":"维吾尔族","value":"UG","num":"05"},
    {"label":"塔吉克族","value":"TA","num":"41"},
    {"label":"塔塔尔族","value":"TT","num":"50"},
    {"label":"朝鲜族","value":"CS","num":"10"},
    {"label":"景颇族","value":"JP","num":"28"},
    {"label":"傣族","value":"DA","num":"18"},
    {"label":"傈僳族","value":"LS","num":"20"},
    {"label":"畲族","value":"SH","num":"22"},
    {"label":"普米族","value":"PM","num":"40"},
    {"label":"裕固族","value":"YG","num":"48"},
    {"label":"蒙古族","value":"MG","num":"02"},
    {"label":"锡伯族","value":"XB","num":"38"},
    {"label":"满族","value":"MA","num":"11"},
    {"label":"瑶族","value":"YA","num":"13"},
    {"label":"赫哲族","value":"HZ","num":"53"},
    {"label":"撒拉族","value":"SL","num":"35"},
    {"label":"德昂族","value":"DE","num":"46"},
    {"label":"黎族","value":"LI","num":"19"},
    {"label":"藏族","value":"ZA","num":"04"},
    {"label":"彝族","value":"YI","num":"07"}
];

export const face = [
    { value: "01", label: "中共党员"},
    { value: "02", label: "中共预备党员"},
    { value: "03", label: "共青团员"},
    { value: "04", label: "民革会员"},
    { value: "05", label: "民盟盟员"},
    { value: "06", label: "民建会员"},
    { value: "07", label: "民进会员"},
    { value: "08", label: "农工党党员"},
    { value: "09", label: "致公党党员"},
    { value: "10", label: "九三学社社员"},
    { value: "11", label: "台盟盟员"},
    { value: "12", label: "无党派民主人士"},
    { value: "13", label: "群众"}
]

export const education = [
    { label: "小学", value: "primary_school" },
    { label: "初中", value: "junior_middle" },
    { label: "中专/高中", value: "secondary_specialized" },
    { label: "专科", value: "specialty" },
    { label: "本科", value: "undergraduate" },
    { label: "硕士", value: "master" },
    { label: "博士", value: "doctor" }
]